-- On insère les pôles de la Fondation --
INSERT INTO Poles (Intitule_Poles, Description_Poles) VALUES 
    ("pspdsa", "Pole sud-Alsace"),
    ("pspdca", "Pole centre-Alsace"),
    ("pspdna", "Pole nord-Alsace")
;  
-- On insère les Etablissemnts de la Fondation --
INSERT INTO etablissements (Intitule_Etablissements, Adresse_Etablissements, Ville_Etablissements, CodePostal_Etablissements, Cle_Poles) VALUES
    ("Clinique du Diaconat Roosevelt", "14 boulevard Roosevelt", "MULHOUSE", 68100, 1),
    ("Clinique du Diaconat Fonderie", "1 rue Saint Sauveur", "MULHOUSE", 68054, 1),
    ("Saint Jean soins de suite", "1 Grande rue", "SENTHEIM", 68780, 1),
    ("Diaconat Domisoins", "2 rue Jean Schlumberger", "GUEBWILLER", 68500, 1),
    ("EHPAD les Violettes", "22 Faubourg de Mulhouse", "KINGERSHEIM", 68260, 1),
    ("Hôpital Albert Schweitzer", "201 Avenue d\'Alsace", "COLMAR", 68000, 2),
    ("Clinique du Diaconat Colmar", "18 rue Charles Sandheer", "COLMAR", 68000, 2),
    ("Home du Florimont", "1 rue de la promenade", "INGERSHEIM", 68040, 2),
    ("Hôpital le Neuenberg", "38 rue Pasteur Hermann", "INGWILLER", 67340, 3),
    ("CSMRA Château Walk", "1 rue du château Walk", "HAGUENAU", 67500, 3),
    ("Solidarités Adultes et Familles", "89 Avenue de Colmar", "STRASBOURG", 67100, 2),
    ("Foyer de l'adolescent", "114 route de Lyon", "ILLKIRCH GRAFFENSTADEN", 67400, 3),
    ("EHPAD Notre Dame des Apôtres", "34 rue Bartholdi", "COLMAR", 68000, 2),
    ("Maison de retraite Saint Joseph", "10 rue de l'Abbé Bidaine", "GIROMAGNY", 90200, NULL)
;
-- On insère les Services de la Fondation --
INSERT INTO `services` (`Intitule_Services`, `Cle_Etablissements`) VALUES
    ("En formation", 10),
    ("Service soignant", 10),
    ("Service économique", 7),
    ("Informatique", 7),
    ("Stérilisation", 2),
    ("Bloc opératoire", 2),
    ("En formation", 9),
    ("Centre de périnatalité", 9),
    ("Chirurgie A", 1),
    ("Chirurgie B", 1),
    ("Brancarder chirugie", 1),
    ("Administration", 1),
    ("Chirurgie ambulatorie", 6),
    ("USICAR", 6),
    ("AHS - Obstetrique", 6),
    ("COVID", 3),
    ("PERSONNEL MEDICAL CDD", 3)
;

-- On insère les diplomes --
INSERT INTO `diplomes` (`Intitule_Diplomes`, `Description_Diplomes`) VALUES
    ("Diplôme d'état français d'infirmier", "Personnel médical: true, Num d'inscription à l'ordre: true, Abrégé gestion documentaire: IDE"),
    ("Diplôme d'état français d'infirmier anesthésiste", "Personnel médical: true, Num d'inscription à l'ordre: true, Abrégé gestion documentaire: IADE"),
    ("Diplôme d'état français d'infirmier de bloc opératoire", "Personnel médical: true, Num d'inscription à l'ordre: true, Abrégé gestion documentaire: IBODE"),
    ("Diplôme d'état français de cadre de santé", "Personnel médical: true, Num d'inscription à l'ordre: true, Abrégé gestion documentaire: CS"),
    ("Diplôme d'état français d'infirmier puericulteur", "Personnel médical: true, Num d'inscription à l'ordre: true, Abrégé gestion documentaire: IP"),
    ("Diplôme d'état français de masseur-kinesitherapeute", "Personnel médical: true, Num d'inscription à l'ordre: true, Abrégé gestion documentaire: KINE"),
    ("Diplôme équivalent d'un pays membre de l'EEE pour la profession d'infirmier", "Personnel médical: true, Num d'inscription à l'ordre: true, Abrégé gestion documentaire: IDE"),
    ("Diplôme équivalent d'un pays membre de l'EEE pour la profession de masseur-kinesitherapeute", "Personnel médical: true, Num d'inscription à l'ordre: true, Abrégé gestion documentaire: KINE"),
    ("Autorisation ministérielle de plein exercice", "Personnel médical: true, Num d'inscription à l'ordre: true, Abrégé gestion documentaire: "),
    ("Aide soignant D.E.", "Personnel médical: true, Num d'inscription à l'ordre: true, Abrégé gestion documentaire: AS"),
    ("Sage Femme D.E.", "Personnel médical: true, Num d'inscription à l'ordre: true, Abrégé gestion documentaire: SF"),
    ("Diplôme d’études spécialisées de médecine générale", "Personnel médical: true, Num d'inscription à l'ordre: true, Abrégé gestion documentaire: Médecin"),
    ("Diplôme d’Etat de docteur en médecine", "Personnel médical: true, Num d'inscription à l'ordre: true, Abrégé gestion documentaire: Médecin"),
    ("Diplôme d'état français de pédicure-podologue", "Personnel médical: true, Num d'inscription à l'ordre: true, Abrégé gestion documentaire: "),
    ("Diplôme équivalent d'un pays membre de l'EEE pour la profession de pédicure-podologue", "Personnel médical: true, Num d'inscription à l'ordre: true, Abrégé gestion documentaire: "),
    ("Capacité de médecine de gérontologie", "Personnel médical: true, Num d'inscription à l'ordre: true, Abrégé gestion documentaire: "),
    ("Auxiliaire de puériculture D.E.", "Personnel médical: true, Num d'inscription à l'ordre: true, Abrégé gestion documentaire: AP"),
    ("Baccalauréat général", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("Baccalauréat professionnel", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("BAFA", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("BEATEP", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("BEP", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("BTS", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("Brevet des Collèges", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("C.P. surveillant de nuit qualifié", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("CAFDES", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("CAFERUIS", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("CAFIME", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("CAP", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("CFP", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("CFP M138", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("CPNE", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("DAEU-A", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("DALF C1", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("DE", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("DEES", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("DEFA", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("DEME", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("DESS", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("DEUST", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("DPLG", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("DU RESMS", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("DUT", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("Licence", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("Licence Pro", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("Maitre apprentissage", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("Maitrise", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("Manipulateur d'électroradiologie médicale", "Personnel médical: true, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("Master", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("Master 1", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: "),
    ("Master 2", "Personnel médical: false, Num d'inscription à l'ordre: false, Abrégé gestion documentaire: ")
;

-- On nisère les postes --
INSERT INTO `postes` (`Intitule_Postes`, `Intitule_Feminin_Postes`) VALUES
    ("A.SOCIAL SPEC.ENFANCE INADAPT.", "ASSISTANTE SOCIALE SPEC.ENFANCE INADAPT."),
    ("ACCOMPAGNANT EDUCATIF SOCIAL", "ACCOMPAGNANTE EDUCATIVE ET SOCIAL"),
    ("ACCUEILLANT SOCIAL", "ACCUEILLANTE SOCIALE"),
    ("ADJ. RESPONSABLE SERV. ECONOM.", "ADJOINTE RESPONSABLE DES SERVICES ECONOMIQUES"),
    ("AGENT ADMINISTRATIF", "AGENTE ADMINISTRATIVE"),
    ("AGENT ADMINISTRATIF PRINCIPAL", "AGENTE ADMINISTRATIVE PRINCIPAL"),
    ("AGENT DE MAINTENANCE", "AGENTE DE MAINTENANCE"),
    ("AGENT DE SERVICE HOSPITALIER", "AGENTE DE SERVICE HOSPITALIER"),
    ("AGENT DE SOINS", "AGENT DE SOINS"),
    ("AGENT DES SERVICES DE SECURITE", "AGENTE DES SERVICES DE SECURITE"),
    ("AGENT DES SERVICES DE SOINS", "AGENTE DES SERVICES DE SOINS"),
    ("AGENT DES SERVICES TECHNIQUES", "AGENTE DES SERVICES TECHNIQUES"),
    ("AGENT HOTELIER SPECIALISE", "AGENTE HOTELIERE SPECIALISEE"),
    ("AGENT SERVICES LOGISTIQUES N1", "AGENTE SERVICES LOGISTIQUES N1"),
    ("AGENT SERVICES LOGISTIQUES N2", "AGENTE SERVICES LOGISTIQUES N2"),
    ("AIDE MEDICO PSYCHOLOGIQUE", "AIDE MEDICO PSYCHOLOGIQUE"),
    ("AIDE-SOIGNANT", "AIDE-SOIGNANTE"),
    ("ANIMATEUR", "ANIMATRICE"),
    ("ANIMATEUR 1ERE CATEGORIE", "ANIMATRICE 1ERE CATEGORIE"),
    ("ANIMATEUR 2EME CATEGORIE", "ANIMATRICE 2EME CATEGORIE"),
    ("ANIMATEUR SOCIO-CULTUREL", "ANIMATRICE SOCIO-CULTUREL"),
    ("ANIMATEUR SOCIO-EDUCATIF", "ANIMATRICE SOCIO-EDUCATIVE"),
    ("ANIMATEUR SOCIO-EDUCATIF N1", "ANIMATRICE SOCIO-EDUCATIVE N1"),
    ("APPRENTI", "APPRENTIE"),
    ("ASSISTANT ADMINISTRATIF", "ASSISTANTE ADMINISTRATIVE"),
    ("ASSISTANT GESTIONNAIRE DE FLUX", "ASSISTANTE GESTIONNAIRE DE FLUX"),
    ("ASSISTANT QUALITE", "ASSISTANTE QUALITE"),
    ("ASSISTANT SOCIAL", "ASSISTANTE SOCIALE"),
    ("ASSISTANT FORMATION", "ASSISTANTE FORMATION"),
    ("AUMONIERE", "AUMONIER"),
    ("AUXILIAIRE DE PUERICULTURE", "AUXILIAIRE DE PUERICULTURE"),
    ("AUXILIAIRE DE VIE", "AUXILIAIRE DE VIE"),
    ("AUXILIAIRE DE VIE DIPLÔME", "AUXILIAIRE DE VIE DIPLOMEE"),
    ("AUXILIAIRE SOCIO - EDUCATIF", "AUXILIAIRE SOCIO - EDUCATIF"),
    ("BIOLOGISTE MEDICAL", "BIOLOGISTE MEDICAL"),
    ("BRANCARDIER", "BRANCARDIERE"),
    ("CADRE ADMINISTRA.ET DE GESTION", "CADRE ADMINISTRA.ET DE GESTION"),
    ("CADRE ADMINISTRATIF NIVEAU 1", "CADRE ADMINISTRATIVE NIVEAU 1"),
    ("CADRE ADMINISTRATIF NIVEAU 3", "CADRE ADMINISTRATIVE NIVEAU 3"),
    ("CADRE COORDINATEUR DES SOINS", "CADRE COORDINATRICE DES SOINS"),
    ("CADRE COORDINATEUR EN HYGIENE", "CADRE COORDINATRICE EN HYGIENE"),
    ("CADRE DE GESTION DES SOINS", "CADRE DE GESTION DES SOINS"),
    ("CADRE DE SANTE", "CADRE DE SANTE"),
    ("CADRE ENSEIGNEMENT DE SANTE", "CADRE ENSEIGNEMENT DE SANTE"),
    ("CADRE INFIRMIER", "CADRE INFIRMIERE HYGIENISTE"),
    ("CADRE INFIRMIER HYGIENISTE", "CADRE INFIRMIERE HYGIENISTE"),
    ("CADRE INFORMATICIEN NIVEAU 2", "CADRE INFORMATICIENNE NIVEAU 2"),
    ("CADRE LOGISTIQUE", "CADRE LOGISTIQUE"),
    ("CADRE MEDICO-TECHNIQUE", "CADRE MEDICO-TECHNIQUE"),
    ("CADRE TECHNIQUE", "CADRE TECHNIQUE"),
    ("CHARGE DE COMMUNICATION", "CHARGEE DE COMMUNICATION"),
    ("CHARGÉ DE PROJETS/DEV.FORMAT.P", "CHARGEE DE PROJETS/DEV.FORMAT.P"),
    ("CHEF COMPTABLE", "CHEFFE COMPTABLE"),
    ("CHEF DE BUREAU", "CHEFFE DE BUREAU"),
    ("CHEF DE CUISINE", "CHEFFE DE CUISINE"),
    ("CHEF DE SER. TECH. BIOMEDICAL", "CHEFFE DE SER. TECH. BIOMEDICAL"),
    ("CHEF DE SERVICE", "CHEFFE DE SERVICE"),
    ("CHEF DE SERVICE ADJOINT", "CHEFFE DE SERVICE ADJOINT"),
    ("CHEF DE SERVICE ADM. NIVEAU 2", "CHEFFE DE SERVICE ADM. NIVEAU 2"),
    ("CHEF DU SERVICE ENTRETIEN", "CHEFFE DU SERVICE ENTRETIEN"),
    ("CHEF SERV.EDUC.CLASSE2 NIV3", "CHEFFE SERV.EDUC.CLASSE2 NIV4"),
    ("COMPTABLE", "COMPTABLE"),
    ("CONSEILLER EN ECO.SOC.ET FAM.", "CONSEILLERE EN ECO.SOC.ET FAM."),
    ("CONSEILLER EN INSERTION", "CONSEILLERE EN INSERTION"),
    ("CONTRAT PROF. AS", "CONTRAT PROF. AS"),
    ("CONTROLEUR DE GESTION N1", "CONTROLEUR DE GESTION N2"),
    ("COORDINAT. QUALITE ET RISQUES", "COORDINATRICE QUALITE ET RISQUES"),
    ("COORDINATEUR GENER. DES SOINS", "COORDINATRICE GENER. DES SOINS"),
    ("COORDINATEUR VIE SOC./HOTEL.", "COORDINATRICE VIE SOC./HOTEL."),
    ("COORDONNATEUR MEDICAL", "COORDONNATEUR MEDICAL"),
    ("DIETETICIENNE", "DIETETICIENNE"),
    ("DIRECTEUR", "DIRECTRICE"),
    ("DIRECTEUR DELEGUE LABO", "DIRECTRICE DELEGUEE LABO"),
    ("DIRECTEUR DES SERVICES", "DIRECTRICE DES SERVICES"),
    ("DIRECTEUR DES SERVICES INFORM.", "DIRECTRICE DES SERVICES INFORM."),
    ("DIRECTEUR FINANCIER", "DIRECTRICE FINANCIER"),
    ("DIRECTEUR FONCTIONNEL", "DIRECTRICE FONCTIONNEL"),
    ("DIRECTEUR GENERAL", "DIRECTRICE GENERAL"),
    ("DIRECTEUR LABORATOIRE", "DIRECTRICE LABORATOIRE"),
    ("DIRECTEUR ORGANIS. ET QUALITE", "DIRECTRICE ORGANIS. ET QUALITE"),
    ("DIRECTEUR RESSOURCES HUMAINES", "DIRECTRICE RESSOURCES HUMAINES"),
    ("DIRECTEUR SERVICES DE SOINS", "DIRECTRICE SERVICES DE SOINS"),
    ("DIRECTEUR SERVICES ECONOMIQUES", "DIRECTRICE SERVICES ECONOMIQUES"),
    ("DIRECTEUR-ADJOINT", "DIRECTRICE-ADJOINTE"),
    ("DIRECTRICE ADJOINTE RH", "DIRECTRICE ADJOINTE RH"),
    ("DIRECTRICE COMMUN. ET ARCHIVES", "DIRECTRICE COMMUN. ET ARCHIVES"),
    ("DIRECTRICE DES SOINS", "DIRECTRICE DES SOINS"),
    ("EDUCATEUR SPECIALISE", "EDUCATRICE SPECIALISEE"),
    ("EDUCATEUR SPORTIF", "EDUCATRICE SPORTIVE"),
    ("EDUCATEUR TECHNIQUE", "EDUCATRICE TECHNIQUE"),
    ("EDUCATEUR TECHNIQUE SPECIALISE", "EDUCATRICE TECHNIQUE SPECIALISEE"),
    ("EDUCATEUR", "EDUCATRICE"),
    ("EDUCATRICE SPECIALISEE", "EDUCATRICE SPECIALISEE"),
    ("EMPLOYE", "EMPLOYEE"),
    ("EMPLOYE ADMINISTRATIF", "EMPLOYEE ADMINISTRATIVE."),
    ("EMPLOYE D\'ACCUEIL ET COMMUNICATION", "EMPLOYEE D\'ACCUEIL ET COMMUNICATION"),
    ("EMPLOYE ADM. AIDE COMPTABLE", "EMPLOYEE ADM. AIDE COMPTABLE"),
    ("ENCADRANT D\'UNITÉ DE SOINS", "ENCADRANTE D\'UNITÉ DE SOINS"),
    ("ENCADRANT MEDICO-TECHNIQUE", "ENCADRANTE MEDICO-TECHNIQUE"),
    ("ENCADRANT UNITE DE REEDUCATION", "ENCADRANTE UNITE DE REEDUCATION"),
    ("ENSEIGNANT INSTITUT FORMATION", "ENSEIGNANTE INSTITUT FORMATION"),
    ("ENSEIGNANT SPECIALISE", "ENSEIGNANTE SPECIALISEE"),
    ("ERGOTHERAPEUTE", "ERGOTHERAPEUTE"),
    ("ETUDIANT", "ETUDIANTE"),
    ("FORMATEUR IFSI", "FORMATRICE IFSI"),
    ("HÔTE DE RESTAURATION", "HÔTESSE DE RESTAURATION"),
    ("INF. SPEC. ANESTHESISTE DE", "INF. SPEC. ANESTHESISTE DE"),
    ("INF. SPEC. BLOC OP DE", "INF. SPEC. BLOC OP DE"),
    ("INF.SPE. PUER DE", "INF.SPE. PUER DE"),
    ("INFIRMIER MAJOR", "INFIRMIERE MAJOR"),
    ("INFIRMIER CHEF", "INFIRMIERE CHEFFE"),
    ("INFIRMIER DE", "INFIRMIERE DE"),
    ("INFIRMIER HYGIENISTE", "INFIRMIERE HYGIENISTE"),
    ("INFORMATICIEN", "INFORMATICIENNE"),
    ("INTERNE", "INTERNE"),
    ("MAGASINIER", "MAGASINIERE"),
    ("MAITRE DE MAISON", "MAITRESSE DE MAISON"),
    ("MANIPULATEUR EN ELECTRO-RADIOL", "MANIPULATRICE EN ELECTRO-RADIOL"),
    ("MASSEUR KINE CHEF DE GROUPE", "MASSEUSE KINE CHEF DE GROUPE"),
    ("MASSEUR-KINESITHERAPEUTE", "MASSEUSE-KINESITHERAPEUTE"),
    ("MEDECIN ASSIST. NON SPECIALISE", "MEDECIN ASSIST. NON SPECIALISEE"),
    ("MEDECIN ASSISTANT", "MEDECIN ASSISTANTE"),
    ("MEDECIN ASSISTANT SPECIALISE", "MEDECIN ASSISTANTE SPECIALISEE"),
    ("MEDECIN ATTACHE", "MEDECIN ATTACHE"),
    ("MEDECIN GENERALISTE", "MEDECIN GENERALISTE"),
    ("MEDECIN SPECIALISE", "MEDECIN SPECIALISE"),
    ("MEDECIN SPECIALISTE", "MEDECIN SPECIALISTE"),
    ("MEDECIN VACATAIRE", "MEDECIN VACATAIRE"),
    ("MEDECIN-BIOLOGISTE", "MEDECIN-BIOLOGISTE"),
    ("MONITEUR ADJOINT D\'ACTIVITES", "MONITRICE ADJOINTE D\'ACTIVITES"),
    ("MONITEUR D\'ATELIER", "MONITRICE D\'ATELIER"),
    ("MONITEUR-EDUCATEUR", "MONITRICE-EDUCATEUR"),
    ("MONITEUR IFAS", "MONITRICE IFAS"),
    ("ORTHOPHONISTE", "ORTHOPHONISTE"),
    ("OUVRIER D\'ENTRETIEN", "OUVRIERE D\'ENTRETIEN"),
    ("OUVRIER HAUT. QUALIFIE", "OUVRIERE HAUT. QUALIFIEE"),
    ("OUVRIER SERV.LOGISTIQUES N1", "OUVRIERE SERV.LOGISTIQUES N1"),
    ("OUVRIER SERV.LOGISTIQUES N2", "OUVRIERE SERV.LOGISTIQUES N2"),
    ("PHARMACIEN BIOLOGISTE DELEGUE", "PHARMACIENNE BIOLOGISTE DELEGUEE"),
    ("PHARMACIEN CHEF DE SERVICE", "PHARMACIENNE CHEFFE DE SERVICE"),
    ("PHARMACIEN", "PHARMACIENNE"),
    ("PREPARATEUR EN PHARMACIE", "PREPARATRICE EN PHARMACIE"),
    ("PREPARATRICE EN PHARMACIE", "PREPARATRICE EN PHARMACIE"),
    ("PSYCHIATRE", "PSYCHIATRE"),
    ("PSYCHOLOGUE", "PSYCHOLOGUE"),
    ("PSYCHOMOTRICIEN(NE)", "PSYCHOMOTRICIEN(NE)"),
    ("RADIO-PHARMACIEN", "RADIO-PHARMACIEN"),
    ("REDACTEUR", "REDACTEUR"),
    ("REFERENT ACCOMP. JURIDIQUE", "REFERENTE ACCOMP. JURIDIQUE"),
    ("REFERENT ASL", "REFERENTE ASL"),
    ("REFERENT TECHNIQUE", "REFERENTE TECHNIQUE"),
    ("RESP. QUALITE ET GEST. RISQUES", "RESP. QUALITE ET GEST. RISQUES"),
    ("RESPONSABLE ADJOINTE ACCUEIL", "RESPONSABLE ADJOINTE ACCUEIL"),
    ("RESPONSABLE ADM. ET FINANCIER", "RESPONSABLE ADM. ET FINANCIER"),
    ("RESPONSABLE DE LA MAINTENANCE", "RESPONSABLE DE LA MAINTENANCE"),
    ("RESPONSABLE HOTELIER", "RESPONSABLE HOTELIER"),
    ("RESPONSABLE INFIRMIER", "RESPONSABLE INFIRMIER"),
    ("RESPONSABLE LOGISTIQUE NIV.1", "RESPONSABLE LOGISTIQUE NIV.1"),
    ("RESPONSABLE LOGISTIQUE NIV.2", "RESPONSABLE LOGISTIQUE NIV.2"),
    ("RESPONSABLE LOGISTIQUE NIV.3", "RESPONSABLE LOGISTIQUE NIV.3"),
    ("RESPONSABLE SECRETARIAT MEDIC.", "RESPONSABLE SECRETARIAT MEDIC."),
    ("RESPONSABLE SERVICE ACCUEIL", "RESPONSABLE SERVICE ACCUEIL"),
    ("RESPONSABLE SERVICE TECHNIQUE", "RESPONSABLE SERVICE TECHNIQUE"),
    ("RESPONSABLE TRAVAUX", "RESPONSABLE TRAVAUX"),
    ("SAGE FEMME", "SAGE FEMME"),
    ("SAGE FEMME CHEF", "SAGE FEMME CHEFFE"),
    ("SECRETAIRE", "SECRETAIRE"),
    ("SECRETAIRE D\'ACCUEIL", "SECRETAIRE D\'ACCUEIL"),
    ("SECRETAIRE DE DIRECTION", "SECRETAIRE DE DIRECTION"),
    ("SECRETAIRE MEDICALE", "SECRETAIRE MEDICALE"),
    ("STAGIAIRE", "STAGIAIRE"),
    ("SURVEILLANT DE NUIT", "SURVEILLANTE DE NUIT"),
    ("SURVEILLANT DE NUIT QUALIFIE", "SURVEILLANTE DE NUIT QUALIFIEE"),
    ("SURVEILLANT GENERAL", "SURVEILLANTE GENERALE"),
    ("TECHN.DES SERV.LOGISTIQUES", "TECHN.DES SERV.LOGISTIQUES"),
    ("TECHNICIEN", "TECHNICIENNE"),
    ("TECHNICIEN ADMINISTRATIF", "TECHNICIENNE ADMINISTRATIVE"),
    ("TECHNICIEN BIOMEDICAL", "TECHNICIENNE BIOMEDICAL"),
    ("TECHNICIEN DE LABORATOIRE", "TECHNICIENNE DE LABORATOIRE"),
    ("TECHNICIEN DE LABORATOIRE CHEF", "TECHNICIENNE DE LABORATOIRE CHEF"),
    ("TECHNICIEN INFORMATION MEDICAL", "TECHNICIENNE INFORMATION MEDICAL"),
    ("TECHNICIEN INFORMATIQUE", "TECHNICIENNE INFORMATIQUE"),
    ("TECHNICIEN SUPERIEUR", "TECHNICIENNE SUPERIEUR"),
    ("TRAVAILLEUR SOCIAL", "TRAVAILLEUSE SOCIAL"),
    ("TRESORIER ADJOINT", "TRESORIERE ADJOINTE"),
    ("FORMATEUR", "FORMATRICE"),
    ("FF D\'INTERNE EN PHARMACIE", "FF D\'INTERNE EN PHARMACIE")
;


-- On insère les aides au recrutement --
INSERT INTO Aides_au_recrutement (Intitule_Aides_au_recrutement) VALUES 
    ("Bourse d'étude"),
    ("Rachat de bourse d'étude"),
    ("Prime de cooptation")
;
-- On insère les types de contrats --
INSERT INTO Types_de_contrats (Intitule_Types_de_contrats, Description_Types_de_contrats) VALUES 
    ('CDI', 'Contrat à durée indéterminée'), 
    ('CDD', 'Contrat à durée déterminée'), 
    ('Stage', 'Stage en entreprise'),
    ('Alternance', 'Formation réalisée en alternance'), 
    ('Interim', 'Mission réalisé par un prestatère')
;
-- On insère les sources --
INSERT INTO sources (Intitule_Sources) VALUES 
	('Hellowork'), 
    ('Hublo'),
    ('Email'), 
    ('Téléphone')
;   

-- On insère les différents Roles des Utilisateurs --
INSERT INTO Roles (Intitule_Role) VALUES
    ('Propriétaire'),
    ('Administrateur'),
    ('Modérateur'),
    ('Utilisateur'),
    ('Invité')
;
-- On insère les types d'actions des Utilisateurs --
INSERT INTO Types (Intitule_Types) VALUES 
    -- Connexions --
    ('Connexion'),
    ('Déconnexion'), 

    -- Utilisateurs --
    ('Nouvel utilisateur'),
    ('Mise-à-jour utilisateur'), 
    ('Mise-à-jour mot de passe'), 
    ('Réinitialisation mot de passe'), 
    ('Mise-à-jour rôle'), 

    -- candidats --
    ('Nouveau candidat'),
    ('Nouveau rendez-vous'), 
    ('Annulation rendez-vous'), 
    ('Mise-à-jour candidat'), 
    ('Mise-à-jour notation'), 
    ('Mise-à-jour rendez-vous'),

    -- Candidatures -- 
    ('Nouvelle candidature'), 
    ('Nouvelle proposition'), 
    ('Nouveau contrat'), 
    ('Refus candidature'), 
    ('Refus proposition'), 
    ('Démission'), 
    
    -- Fondation --
    ('Nouveau pôle'), 
    ('Nouveau service'), 
    ('Nouvel établissement'), 
    ('Nouveau poste'), 
    ('Nouveau diplome')
;

-- On insère un Utilisateur --
INSERT INTO Utilisateurs (Identifiant_Utilisateurs, Nom_Utilisateurs, Prenom_Utilisateurs, MotDePasse_Utilisateurs, Email_Utilisateurs, Cle_Roles, Cle_Etablissements) VALUES
    ('owner', 'Service informatique', 'Directeur', '$2y$10$GxE1ZTjltfUerJDABRgtLOif/jT1Xpo28CLxb9P./pcvKWJXYis6y', 'yannick.keller@diaconat-mulhouse.fr', 1, 1)
;    